version: "3.9"

networks:
    web:
      external: true
      driver:  bridge

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2g
    framework:
      build: .
      networks:
        - web
      depends_on:
        - chrome
  app:
    build: .
    container_name: E-commerce
    command: >
      sh -c "python3 manage.py makemigrations --noinput && \
                 python3 manage.py migrate --noinput && \
                 python3 manage.py collectstatic --noinput && \
                 python3 manage.py createsuperuser --username superuser --noinput; \
                 python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - pgdata:/var/lib/posgresql/data
volumes:
  pgdata: