version: "3.8"

services:
  web:
    build:
      context: .
    container_name: "BookStore"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
    command: >
      sh -c "python3 manage.py makemigrations --noinput && \
             python3 manage.py migrate --noinput && \
             python3 manage.py collectstatic --noinput && \
             python3 manage.py createsuperuser --user admin --email admin@localhost --noinput; \
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:11
    container_name: "PostgresDB"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=123@456

volumes:
  postgres-data: