# Generated by Django 4.0.6 on 2022-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_cart_remove_profile_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
