# Generated by Django 4.0.6 on 2022-07-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsection',
            options={'ordering': ['-created']},
        ),
    ]
