# Generated by Django 4.0.6 on 2022-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='new_publish',
        ),
        migrations.AddField(
            model_name='book',
            name='count_sold',
            field=models.IntegerField(default=0),
        ),
    ]
