# Generated by Django 4.0.6 on 2022-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_favoritebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_publish',
            field=models.BooleanField(default=False),
        ),
    ]
