# Generated by Django 4.0.6 on 2022-07-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebook',
            name='book_id',
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='book.book'),
        ),
    ]
