# Generated by Django 4.0.6 on 2022-07-15 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_remove_favoritebook_book_id_favoritebook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
