# Generated by Django 4.0.6 on 2022-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookcategory_alter_book_genre_bookcategory_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='bookauthor',
            old_name='author',
            new_name='authors',
        ),
    ]
