# Generated by Django 4.0.6 on 2022-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_favoritebook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebook',
            name='user',
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='user',
            field=models.CharField(default='admin', max_length=25),
            preserve_default=False,
        ),
    ]
