# Generated by Django 4.0.6 on 2022-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_favoritebook_user_favoritebook_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearcHHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('query', models.CharField(max_length=100)),
            ],
        ),
    ]
