# Generated by Django 4.0.6 on 2022-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
