# Generated by Django 4.0.6 on 2022-07-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_searchhistory_user_id'),
        ('cart', '0003_rename_product_cartitem_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.book'),
        ),
    ]
