# Generated by Django 4.0.6 on 2022-07-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_cart_remove_profile_favorite_and_more'),
        ('cart', '0006_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='postal_code',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='cart.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
