# Generated by Django 4.0.6 on 2022-07-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_address_cart_city_cart_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='province',
        ),
    ]
