# Generated by Django 4.0.6 on 2022-08-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentSection',
            new_name='Comment',
        ),
    ]
